name: AI Interlocutor
on:
  push:
    paths:
      - 'main.py'
      - ".github/workflows/workflow.yml"

env:
  EXPECTED_RESPONSE: "The task is completed."
  TASK_FOLDER: "${{ github.workspace }}"
  IMAGE_NAME: "ai_interlocutor"
  CONTAINER_NAME: "app-container"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if directory exists
        run: |
          if [ -d ${TASK_FOLDER} ]; then
          echo "Directory exists"
          else
          echo "Directory does not exist"
          exit 1
          fi

      - name: Install project dependencies
        run: |
          pip install --no-cache-dir -r "${{ env.TASK_FOLDER }}/requirements.txt"
          pip3 install torch --index-url https://download.pytorch.org/whl/cu118
          pip install ffmpeg-downloader==0.3.0
          ffdl install -y

      - name: Run tests
        run: python -m unittest -v

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3